pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'echo "Hello World"'
                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                '''
            }
        }
        stage('Compile-package') {
            steps {
            	def M2_HOME = tool name: 'MAVEN3_6_3', type: 'maven'
                sh "${M2_HOME}/bin/mvn package"
            }
        }
    }
}