pipeline {
    agent any
    tools { 
       maven 'MAVEN3_6_3'
       jdk 'JAVA11'
    }
    stages {
    	stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        stage('Print') {
            steps {
                sh 'echo "Hello World"'
                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                '''
            }
        }
        stage('Compile-package') {
        	steps {
        			sh '''
                        cd CamelSample
                        pwd
                	    mvn package
                    '''
        	}
        }
        stage('Deploy') {
        	steps {
        			sh 'cp -r target/CamelSample-0.0.1-SNAPSHOT.jar /home/borokali/CamelSample/.'
        	}
        }
    }
}
