pipeline {
    agent any
    tools { 
       maven 'MAVEN3_6_3'
       jdk 'JAVA11'
    }
    stages {
    	stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH = ${PATH}"
                    echo "M2_HOME = ${M2_HOME}"
                '''
            }
        }
        stage('Print') {
            steps {
                sh 'echo "Hello World"'
                sh '''
                    echo "Multiline shell steps works too"
                    ls -lah
                '''
            }
        }
        stage('Compile-package') {
        	steps {
        			sh '''
                        cd CamelSample
                        pwd
                	    mvn package
                    '''
        	}
        }
        stage('Transfer') {
        	steps {
        			sh '''
                    cd CamelSample/target
                    rm -rf /home/borokali/CamelSample/*.jar
                    cp -r *.jar /home/borokali/CamelSample/.
                    '''
        	}
        }
        stage('Deploy') {
        	steps {
        			sh 'cd /home/borokali/CamelSample'
                    sh 'sh kill_boot.sh'
                    sh 'JENKINS_NODE_COOKIE=dontKillMe nohup sh deploy.sh 8088 &'
        	}
        }
    }
}
